version: '2'
name: ai-chatbot
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: trgn312/ai-chatbot_frontend:latest
    hostname: frontend
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: trgn312/ai-chatbot_backend:latest
    hostname: backend
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        fastapi run --host 0.0.0.0 --port 80 --root-path /api
    environment:
      MONGODB_HOST: mongodb://mongodb:27017
      APPLICATION_ENV: Production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2.20
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data

  gateway:
    image: nginx:1.13.3-alpine
    hostname: gateway
    volumes:
      - ./scripts/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  mongodbdata: